// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as CheckRouteImport } from './routes/check'
import { Route as SelenaRouteImport } from './routes/selena'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as AuthedChoosePlanRouteImport } from './routes/_authed/choose-plan'
import { Route as AuthedFreeAiVisibilityRouteImport } from './routes/_authed/free-ai-visibility'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AppLearnRouteImport } from './routes/app/learn'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthedAcceptInvitationInvitationIdRouteImport } from './routes/_authed/accept-invitation/$invitationId'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminProvidersRouteImport } from './routes/_authed/admin/providers'
import { Route as AuthedAdminToolsRouteImport } from './routes/_authed/admin/tools'
import { Route as AuthedAdminWorkflowsRouteImport } from './routes/_authed/admin/workflows'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/app/index'
import { Route as AuthedAppBrandRouteImport } from './routes/_authed/app/$brand'
import { Route as AuthedAppAcademyRouteImport } from './routes/_authed/app/academy'
import { Route as AuthedAppNewRouteImport } from './routes/_authed/app/new'
import { Route as AuthedAppSelenaRouteImport } from './routes/_authed/app/selena'
import { Route as AuthedAppSelenaAdminRouteImport } from './routes/_authed/app/selena-admin'
import { Route as AuthedAppSelenaHorecaRouteImport } from './routes/_authed/app/selena-horeca'
import { Route as AuthedAppSelenaOrderRouteImport } from './routes/_authed/app/selena-order'
import { Route as AuthedAppSelenaReportRouteImport } from './routes/_authed/app/selena-report'
import { Route as AuthedAppSelenaSourcesRouteImport } from './routes/_authed/app/selena-sources'
import { Route as AuthedReportsIndexRouteImport } from './routes/_authed/reports/index'
import { Route as AuthedAppBrandIndexRouteImport } from './routes/_authed/app/$brand/index'
import { Route as AuthedAppBrandSplatRouteImport } from './routes/_authed/app/$brand/$'
import { Route as AuthedAppBrandCitationsRouteImport } from './routes/_authed/app/$brand/citations'
import { Route as AuthedAppBrandOpportunitiesRouteImport } from './routes/_authed/app/$brand/opportunities'
import { Route as AuthedAppBrandQueryFanOutRouteImport } from './routes/_authed/app/$brand/query-fan-out'
import { Route as AuthedAppBrandShareOfVoiceRouteImport } from './routes/_authed/app/$brand/share-of-voice'
import { Route as AuthedAppBrandVisibilityRouteImport } from './routes/_authed/app/$brand/visibility'
import { Route as AuthedReportsRenderReportIdRouteImport } from './routes/_authed/reports/render/$reportId'
import { Route as AuthedSelenaLocalCycleIdRouteImport } from './routes/_authed/selena/local/$cycleId'
import { Route as AuthedSelenaLocalCheckoutRouteImport } from './routes/_authed/selena/local/checkout'
import { Route as ApiV1DocsIndexRouteImport } from './routes/api/v1/docs/index'
import { Route as AuthedAppBrandPromptsIndexRouteImport } from './routes/_authed/app/$brand/prompts/index'
import { Route as AuthedAppBrandPromptsPromptIdRouteImport } from './routes/_authed/app/$brand/prompts/$promptId'
import { Route as AuthedAppBrandPromptsEditRouteImport } from './routes/_authed/app/$brand/prompts/edit'
import { Route as AuthedAppBrandSettingsIndexRouteImport } from './routes/_authed/app/$brand/settings/index'
import { Route as AuthedAppBrandSettingsBillingRouteImport } from './routes/_authed/app/$brand/settings/billing'
import { Route as AuthedAppBrandSettingsBrandRouteImport } from './routes/_authed/app/$brand/settings/brand'
import { Route as AuthedAppBrandSettingsCompetitorsRouteImport } from './routes/_authed/app/$brand/settings/competitors'
import { Route as AuthedAppBrandSettingsLlmsRouteImport } from './routes/_authed/app/$brand/settings/llms'
import { Route as AuthedAppBrandSettingsMembersRouteImport } from './routes/_authed/app/$brand/settings/members'
import { Route as AuthedAppBrandSettingsPromptsRouteImport } from './routes/_authed/app/$brand/settings/prompts'

const IndexRoute = IndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => rootRouteImport
          })
const AuthedRoute = AuthedRouteImport.update({
            id: '/_authed',getParentRoute: () => rootRouteImport
          })
const CheckRoute = CheckRouteImport.update({
            id: '/check',path: '/check',getParentRoute: () => rootRouteImport
          })
const SelenaRoute = SelenaRouteImport.update({
            id: '/selena',path: '/selena',getParentRoute: () => rootRouteImport
          })
const AuthedAdminRoute = AuthedAdminRouteImport.update({
            id: '/admin',path: '/admin',getParentRoute: () => AuthedRoute
          })
const AuthedAppRoute = AuthedAppRouteImport.update({
            id: '/app',path: '/app',getParentRoute: () => AuthedRoute
          })
const AuthedChoosePlanRoute = AuthedChoosePlanRouteImport.update({
            id: '/choose-plan',path: '/choose-plan',getParentRoute: () => AuthedRoute
          })
const AuthedFreeAiVisibilityRoute = AuthedFreeAiVisibilityRouteImport.update({
            id: '/free-ai-visibility',path: '/free-ai-visibility',getParentRoute: () => AuthedRoute
          })
const AuthedReportsRoute = AuthedReportsRouteImport.update({
            id: '/reports',path: '/reports',getParentRoute: () => AuthedRoute
          })
const AppLearnRoute = AppLearnRouteImport.update({
            id: '/app/learn',path: '/app/learn',getParentRoute: () => rootRouteImport
          })
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
            id: '/auth/forgot-password',path: '/auth/forgot-password',getParentRoute: () => rootRouteImport
          })
const AuthLoginRoute = AuthLoginRouteImport.update({
            id: '/auth/login',path: '/auth/login',getParentRoute: () => rootRouteImport
          })
const AuthRegisterRoute = AuthRegisterRouteImport.update({
            id: '/auth/register',path: '/auth/register',getParentRoute: () => rootRouteImport
          })
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
            id: '/auth/reset-password',path: '/auth/reset-password',getParentRoute: () => rootRouteImport
          })
const AuthedAcceptInvitationInvitationIdRoute = AuthedAcceptInvitationInvitationIdRouteImport.update({
            id: '/accept-invitation/$invitationId',path: '/accept-invitation/$invitationId',getParentRoute: () => AuthedRoute
          })
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => AuthedAdminRoute
          })
const AuthedAdminProvidersRoute = AuthedAdminProvidersRouteImport.update({
            id: '/providers',path: '/providers',getParentRoute: () => AuthedAdminRoute
          })
const AuthedAdminToolsRoute = AuthedAdminToolsRouteImport.update({
            id: '/tools',path: '/tools',getParentRoute: () => AuthedAdminRoute
          })
const AuthedAdminWorkflowsRoute = AuthedAdminWorkflowsRouteImport.update({
            id: '/workflows',path: '/workflows',getParentRoute: () => AuthedAdminRoute
          })
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppBrandRoute = AuthedAppBrandRouteImport.update({
            id: '/$brand',path: '/$brand',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppAcademyRoute = AuthedAppAcademyRouteImport.update({
            id: '/academy',path: '/academy',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppNewRoute = AuthedAppNewRouteImport.update({
            id: '/new',path: '/new',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppSelenaRoute = AuthedAppSelenaRouteImport.update({
            id: '/selena',path: '/selena',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppSelenaAdminRoute = AuthedAppSelenaAdminRouteImport.update({
            id: '/selena-admin',path: '/selena-admin',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppSelenaHorecaRoute = AuthedAppSelenaHorecaRouteImport.update({
            id: '/selena-horeca',path: '/selena-horeca',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppSelenaOrderRoute = AuthedAppSelenaOrderRouteImport.update({
            id: '/selena-order',path: '/selena-order',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppSelenaReportRoute = AuthedAppSelenaReportRouteImport.update({
            id: '/selena-report',path: '/selena-report',getParentRoute: () => AuthedAppRoute
          })
const AuthedAppSelenaSourcesRoute = AuthedAppSelenaSourcesRouteImport.update({
            id: '/selena-sources',path: '/selena-sources',getParentRoute: () => AuthedAppRoute
          })
const AuthedReportsIndexRoute = AuthedReportsIndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => AuthedReportsRoute
          })
const AuthedAppBrandIndexRoute = AuthedAppBrandIndexRouteImport.update({
            id: '/',path: '/',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandSplatRoute = AuthedAppBrandSplatRouteImport.update({
            id: '/$',path: '/$',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandCitationsRoute = AuthedAppBrandCitationsRouteImport.update({
            id: '/citations',path: '/citations',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandOpportunitiesRoute = AuthedAppBrandOpportunitiesRouteImport.update({
            id: '/opportunities',path: '/opportunities',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandQueryFanOutRoute = AuthedAppBrandQueryFanOutRouteImport.update({
            id: '/query-fan-out',path: '/query-fan-out',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandShareOfVoiceRoute = AuthedAppBrandShareOfVoiceRouteImport.update({
            id: '/share-of-voice',path: '/share-of-voice',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandVisibilityRoute = AuthedAppBrandVisibilityRouteImport.update({
            id: '/visibility',path: '/visibility',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedReportsRenderReportIdRoute = AuthedReportsRenderReportIdRouteImport.update({
            id: '/render/$reportId',path: '/render/$reportId',getParentRoute: () => AuthedReportsRoute
          })
const AuthedSelenaLocalCycleIdRoute = AuthedSelenaLocalCycleIdRouteImport.update({
            id: '/selena/local/$cycleId',path: '/selena/local/$cycleId',getParentRoute: () => AuthedRoute
          })
const AuthedSelenaLocalCheckoutRoute = AuthedSelenaLocalCheckoutRouteImport.update({
            id: '/selena/local/checkout',path: '/selena/local/checkout',getParentRoute: () => AuthedRoute
          })
const ApiV1DocsIndexRoute = ApiV1DocsIndexRouteImport.update({
            id: '/api/v1/docs/',path: '/api/v1/docs/',getParentRoute: () => rootRouteImport
          })
const AuthedAppBrandPromptsIndexRoute = AuthedAppBrandPromptsIndexRouteImport.update({
            id: '/prompts/',path: '/prompts/',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandPromptsPromptIdRoute = AuthedAppBrandPromptsPromptIdRouteImport.update({
            id: '/prompts/$promptId',path: '/prompts/$promptId',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandPromptsEditRoute = AuthedAppBrandPromptsEditRouteImport.update({
            id: '/prompts/edit',path: '/prompts/edit',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandSettingsIndexRoute = AuthedAppBrandSettingsIndexRouteImport.update({
            id: '/settings/',path: '/settings/',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandSettingsBillingRoute = AuthedAppBrandSettingsBillingRouteImport.update({
            id: '/settings/billing',path: '/settings/billing',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandSettingsBrandRoute = AuthedAppBrandSettingsBrandRouteImport.update({
            id: '/settings/brand',path: '/settings/brand',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandSettingsCompetitorsRoute = AuthedAppBrandSettingsCompetitorsRouteImport.update({
            id: '/settings/competitors',path: '/settings/competitors',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandSettingsLlmsRoute = AuthedAppBrandSettingsLlmsRouteImport.update({
            id: '/settings/llms',path: '/settings/llms',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandSettingsMembersRoute = AuthedAppBrandSettingsMembersRouteImport.update({
            id: '/settings/members',path: '/settings/members',getParentRoute: () => AuthedAppBrandRoute
          })
const AuthedAppBrandSettingsPromptsRoute = AuthedAppBrandSettingsPromptsRouteImport.update({
            id: '/settings/prompts',path: '/settings/prompts',getParentRoute: () => AuthedAppBrandRoute
          })





const AuthedAdminRouteChildren = {
  AuthedAdminProvidersRoute: AuthedAdminProvidersRoute,AuthedAdminToolsRoute: AuthedAdminToolsRoute,AuthedAdminWorkflowsRoute: AuthedAdminWorkflowsRoute,AuthedAdminIndexRoute: AuthedAdminIndexRoute
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(AuthedAdminRouteChildren)




const AuthedAppBrandRouteChildren = {
  AuthedAppBrandSplatRoute: AuthedAppBrandSplatRoute,AuthedAppBrandCitationsRoute: AuthedAppBrandCitationsRoute,AuthedAppBrandOpportunitiesRoute: AuthedAppBrandOpportunitiesRoute,AuthedAppBrandQueryFanOutRoute: AuthedAppBrandQueryFanOutRoute,AuthedAppBrandShareOfVoiceRoute: AuthedAppBrandShareOfVoiceRoute,AuthedAppBrandVisibilityRoute: AuthedAppBrandVisibilityRoute,AuthedAppBrandIndexRoute: AuthedAppBrandIndexRoute,AuthedAppBrandPromptsPromptIdRoute: AuthedAppBrandPromptsPromptIdRoute,AuthedAppBrandPromptsEditRoute: AuthedAppBrandPromptsEditRoute,AuthedAppBrandSettingsBillingRoute: AuthedAppBrandSettingsBillingRoute,AuthedAppBrandSettingsBrandRoute: AuthedAppBrandSettingsBrandRoute,AuthedAppBrandSettingsCompetitorsRoute: AuthedAppBrandSettingsCompetitorsRoute,AuthedAppBrandSettingsLlmsRoute: AuthedAppBrandSettingsLlmsRoute,AuthedAppBrandSettingsMembersRoute: AuthedAppBrandSettingsMembersRoute,AuthedAppBrandSettingsPromptsRoute: AuthedAppBrandSettingsPromptsRoute,AuthedAppBrandPromptsIndexRoute: AuthedAppBrandPromptsIndexRoute,AuthedAppBrandSettingsIndexRoute: AuthedAppBrandSettingsIndexRoute
}

const AuthedAppBrandRouteWithChildren = AuthedAppBrandRoute._addFileChildren(AuthedAppBrandRouteChildren)



const AuthedAppRouteChildren = {
  AuthedAppBrandRoute: AuthedAppBrandRouteWithChildren,AuthedAppAcademyRoute: AuthedAppAcademyRoute,AuthedAppNewRoute: AuthedAppNewRoute,AuthedAppSelenaRoute: AuthedAppSelenaRoute,AuthedAppSelenaAdminRoute: AuthedAppSelenaAdminRoute,AuthedAppSelenaHorecaRoute: AuthedAppSelenaHorecaRoute,AuthedAppSelenaOrderRoute: AuthedAppSelenaOrderRoute,AuthedAppSelenaReportRoute: AuthedAppSelenaReportRoute,AuthedAppSelenaSourcesRoute: AuthedAppSelenaSourcesRoute,AuthedAppIndexRoute: AuthedAppIndexRoute
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(AuthedAppRouteChildren)




const AuthedReportsRouteChildren = {
  AuthedReportsIndexRoute: AuthedReportsIndexRoute,AuthedReportsRenderReportIdRoute: AuthedReportsRenderReportIdRoute
}

const AuthedReportsRouteWithChildren = AuthedReportsRoute._addFileChildren(AuthedReportsRouteChildren)



const AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,AuthedAppRoute: AuthedAppRouteWithChildren,AuthedChoosePlanRoute: AuthedChoosePlanRoute,AuthedFreeAiVisibilityRoute: AuthedFreeAiVisibilityRoute,AuthedReportsRoute: AuthedReportsRouteWithChildren,AuthedAcceptInvitationInvitationIdRoute: AuthedAcceptInvitationInvitationIdRoute,AuthedSelenaLocalCycleIdRoute: AuthedSelenaLocalCycleIdRoute,AuthedSelenaLocalCheckoutRoute: AuthedSelenaLocalCheckoutRoute
}

const AuthedRouteWithChildren = AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren = {
  IndexRoute: IndexRoute,AuthedRoute: AuthedRouteWithChildren,CheckRoute: CheckRoute,SelenaRoute: SelenaRoute,AppLearnRoute: AppLearnRoute,AuthForgotPasswordRoute: AuthForgotPasswordRoute,AuthLoginRoute: AuthLoginRoute,AuthRegisterRoute: AuthRegisterRoute,AuthResetPasswordRoute: AuthResetPasswordRoute,ApiV1DocsIndexRoute: ApiV1DocsIndexRoute
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)