import type { ProviderDatasetSourceId } from "../providers/dataset-registry";
import type { BrightDataSocialDatasetConfig, BrightDataSocialDatasetKey } from "./types";

const PUBLIC_PAYG_PER_RECORD_USD = 0.0015;
const COLLECTION_TIMEOUT_MS = 15 * 60_000;
const DOWNLOAD_TIMEOUT_MS = 5 * 60_000;
const MAX_RESPONSE_BYTES = 8 * 1024 * 1024;

/**
 * The eight contracts observed in staging on 2026-08-31. Dataset ids remain
 * sealed environment configuration: importing this registry starts no jobs.
 */
export const brightDataSocialDatasetRegistry = {
	instagram_profiles: {
		key: "instagram_profiles",
		platform: "instagram",
		envKey: "SELENA_BRIGHTDATA_DATASET_INSTAGRAM_PROFILES",
		mode: "collect_by_url",
		inputContract: { required: ["url"], optional: [], maxInputsPerRun: 1 },
		triggerQuery: {},
		metadataSignature: ["id", "followers", "url"],
		stableIdFields: ["id", "fbid", "partner_id"],
		pagination: "none",
		providerOutputCap: "none",
		expectedMaxOutputRecords: 1,
		unitCostUsd: PUBLIC_PAYG_PER_RECORD_USD,
		collectionTimeoutMs: COLLECTION_TIMEOUT_MS,
		downloadTimeoutMs: DOWNLOAD_TIMEOUT_MS,
		maxResponseBytes: MAX_RESPONSE_BYTES,
		runtimeStatus: "eligible_after_project_assignment",
		rawRetention: "disabled",
		personalDataClassification: "public_user_data",
		incrementalStrategy: "Allowlisted profile URLs; upsert by id; store mutable metrics as snapshots.",
		personalDataFields: ["account", "full_name", "biography", "pronouns", "email", "phone", "profile_image"],
	},
	instagram_posts: {
		key: "instagram_posts",
		platform: "instagram",
		envKey: "SELENA_BRIGHTDATA_DATASET_INSTAGRAM_POSTS",
		mode: "collect_by_url",
		inputContract: { required: ["url"], optional: [], maxInputsPerRun: 1 },
		triggerQuery: {},
		metadataSignature: ["post_id", "shortcode", "url"],
		stableIdFields: ["post_id", "pk", "shortcode", "content_id"],
		pagination: "none",
		providerOutputCap: "none",
		expectedMaxOutputRecords: 1,
		unitCostUsd: PUBLIC_PAYG_PER_RECORD_USD,
		collectionTimeoutMs: COLLECTION_TIMEOUT_MS,
		downloadTimeoutMs: DOWNLOAD_TIMEOUT_MS,
		maxResponseBytes: MAX_RESPONSE_BYTES,
		runtimeStatus: "eligible_after_project_assignment",
		rawRetention: "disabled",
		personalDataClassification: "public_user_data",
		incrementalStrategy: "Known URL registry; upsert by post_id; bounded refreshes for mutable engagement.",
		personalDataFields: ["user_posted", "profile_url", "description", "tagged_users", "top_comments", "location"],
	},
	instagram_reels: {
		key: "instagram_reels",
		platform: "instagram",
		envKey: "SELENA_BRIGHTDATA_DATASET_INSTAGRAM_REELS",
		mode: "discover_by_profile_url",
		inputContract: { required: ["url", "num_of_posts"], optional: [], maxInputsPerRun: 1 },
		triggerQuery: { type: "discover_new", discover_by: "url" },
		metadataSignature: ["post_id", "video_url", "video_play_count"],
		stableIdFields: ["post_id", "shortcode", "content_id"],
		pagination: "bounded_num_of_posts",
		providerOutputCap: "num_of_posts",
		expectedMaxOutputRecords: 1,
		unitCostUsd: PUBLIC_PAYG_PER_RECORD_USD,
		collectionTimeoutMs: COLLECTION_TIMEOUT_MS,
		downloadTimeoutMs: DOWNLOAD_TIMEOUT_MS,
		maxResponseBytes: MAX_RESPONSE_BYTES,
		runtimeStatus: "eligible_after_project_assignment",
		rawRetention: "disabled",
		personalDataClassification: "public_user_data",
		incrementalStrategy:
			"Bounded discovery with num_of_posts=1; dedupe by post_id; later add verified date/exclusion inputs.",
		personalDataFields: ["user_posted", "description", "tagged_users", "coauthor_producers", "top_comments"],
	},
	instagram_comments: {
		key: "instagram_comments",
		platform: "instagram",
		envKey: "SELENA_BRIGHTDATA_DATASET_INSTAGRAM_COMMENTS",
		mode: "collect_by_url",
		inputContract: { required: ["url"], optional: [], maxInputsPerRun: 1 },
		triggerQuery: {},
		metadataSignature: ["comment_id", "comment_text", "comment_date"],
		stableIdFields: ["comment_id"],
		pagination: "none",
		providerOutputCap: "unproven",
		expectedMaxOutputRecords: 0,
		unitCostUsd: PUBLIC_PAYG_PER_RECORD_USD,
		collectionTimeoutMs: COLLECTION_TIMEOUT_MS,
		downloadTimeoutMs: DOWNLOAD_TIMEOUT_MS,
		maxResponseBytes: MAX_RESPONSE_BYTES,
		runtimeStatus: "blocked_cost_and_pii",
		rawRetention: "disabled",
		personalDataClassification: "high_volume_public_user_data",
		incrementalStrategy: "Blocked until Bright Data demonstrates a provider-enforced output cap.",
		personalDataFields: ["comment_user", "comment_text", "comment_date", "tagged_users", "replies", "post_user"],
	},
	tiktok_profiles: {
		key: "tiktok_profiles",
		platform: "tiktok",
		envKey: "SELENA_BRIGHTDATA_DATASET_TIKTOK_PROFILES",
		mode: "collect_by_url",
		inputContract: { required: ["url"], optional: [], maxInputsPerRun: 1 },
		triggerQuery: {},
		metadataSignature: ["account_id", "secu_id", "url"],
		stableIdFields: ["account_id", "id", "secu_id"],
		pagination: "none",
		providerOutputCap: "none",
		expectedMaxOutputRecords: 1,
		unitCostUsd: PUBLIC_PAYG_PER_RECORD_USD,
		collectionTimeoutMs: COLLECTION_TIMEOUT_MS,
		downloadTimeoutMs: DOWNLOAD_TIMEOUT_MS,
		maxResponseBytes: MAX_RESPONSE_BYTES,
		runtimeStatus: "eligible_after_project_assignment",
		rawRetention: "disabled",
		personalDataClassification: "public_user_data",
		incrementalStrategy: "Allowlisted profile URLs; upsert by account_id; store mutable metrics as snapshots.",
		personalDataFields: ["nickname", "biography", "signature", "bio_link", "profile_pic_url", "region"],
	},
	tiktok_posts: {
		key: "tiktok_posts",
		platform: "tiktok",
		envKey: "SELENA_BRIGHTDATA_DATASET_TIKTOK_POSTS",
		mode: "collect_by_url",
		inputContract: { required: ["url"], optional: [], maxInputsPerRun: 1 },
		triggerQuery: {},
		metadataSignature: ["post_id", "account_id", "url"],
		stableIdFields: ["post_id", "shortcode"],
		pagination: "none",
		providerOutputCap: "none",
		expectedMaxOutputRecords: 1,
		unitCostUsd: PUBLIC_PAYG_PER_RECORD_USD,
		collectionTimeoutMs: COLLECTION_TIMEOUT_MS,
		downloadTimeoutMs: DOWNLOAD_TIMEOUT_MS,
		maxResponseBytes: MAX_RESPONSE_BYTES,
		runtimeStatus: "eligible_after_project_assignment",
		rawRetention: "disabled",
		personalDataClassification: "public_user_data",
		incrementalStrategy: "Known URL registry; upsert by post_id; bounded refreshes for mutable engagement.",
		personalDataFields: ["account_id", "profile_id", "secu_id", "user_posted", "biography", "tagged_users", "region"],
	},
	reddit_posts: {
		key: "reddit_posts",
		platform: "reddit",
		envKey: "SELENA_BRIGHTDATA_DATASET_REDDIT_POSTS",
		mode: "collect_by_url",
		inputContract: { required: ["url"], optional: [], maxInputsPerRun: 1 },
		triggerQuery: {},
		metadataSignature: ["post_id", "community_name", "url"],
		stableIdFields: ["post_id"],
		pagination: "none",
		providerOutputCap: "none",
		expectedMaxOutputRecords: 1,
		unitCostUsd: PUBLIC_PAYG_PER_RECORD_USD,
		collectionTimeoutMs: COLLECTION_TIMEOUT_MS,
		downloadTimeoutMs: DOWNLOAD_TIMEOUT_MS,
		maxResponseBytes: MAX_RESPONSE_BYTES,
		runtimeStatus: "eligible_after_project_assignment",
		rawRetention: "disabled",
		personalDataClassification: "public_user_data",
		incrementalStrategy: "Known URL enrichment; upstream date watermark; dedupe by post_id.",
		personalDataFields: [
			"user_id",
			"user_posted",
			"bio_description",
			"author_icon",
			"title",
			"description",
			"comments",
		],
	},
	youtube_videos: {
		key: "youtube_videos",
		platform: "youtube",
		envKey: "SELENA_BRIGHTDATA_DATASET_YOUTUBE_VIDEOS",
		mode: "collect_by_url",
		inputContract: { required: ["url"], optional: [], maxInputsPerRun: 1 },
		triggerQuery: {},
		metadataSignature: ["video_id", "youtuber_id", "url"],
		stableIdFields: ["video_id", "shortcode"],
		pagination: "none",
		providerOutputCap: "none",
		expectedMaxOutputRecords: 1,
		unitCostUsd: PUBLIC_PAYG_PER_RECORD_USD,
		collectionTimeoutMs: COLLECTION_TIMEOUT_MS,
		downloadTimeoutMs: DOWNLOAD_TIMEOUT_MS,
		maxResponseBytes: MAX_RESPONSE_BYTES,
		runtimeStatus: "eligible_after_project_assignment",
		rawRetention: "disabled",
		personalDataClassification: "public_user_data",
		incrementalStrategy:
			"Known video registry; upsert by video_id; bounded refreshes for metrics and transcript availability.",
		personalDataFields: [
			"youtuber",
			"channel_handle",
			"channel_avatar",
			"title",
			"description",
			"transcript",
			"comments",
		],
	},
} as const satisfies Record<BrightDataSocialDatasetKey, BrightDataSocialDatasetConfig>;

export function getBrightDataSocialDataset(key: BrightDataSocialDatasetKey): BrightDataSocialDatasetConfig {
	return brightDataSocialDatasetRegistry[key];
}

export const brightDataSocialSourceByKey = Object.freeze({
	instagram_profiles: "INSTAGRAM_PROFILES",
	instagram_posts: "INSTAGRAM_POSTS",
	instagram_reels: "INSTAGRAM_REELS",
	instagram_comments: "INSTAGRAM_COMMENTS",
	tiktok_profiles: "TIKTOK_PROFILES",
	tiktok_posts: "TIKTOK_POSTS",
	reddit_posts: "REDDIT_POSTS",
	youtube_videos: "YOUTUBE_VIDEOS",
} as const satisfies Record<BrightDataSocialDatasetKey, ProviderDatasetSourceId>);

const brightDataSocialKeyBySource = new Map<ProviderDatasetSourceId, BrightDataSocialDatasetKey>(
	Object.entries(brightDataSocialSourceByKey).map(([key, source]) => [source, key as BrightDataSocialDatasetKey]),
);

export function getBrightDataSocialDatasetBySource(source: ProviderDatasetSourceId): BrightDataSocialDatasetConfig {
	const key = brightDataSocialKeyBySource.get(source);
	if (!key) throw new Error(`BRIGHTDATA_SOCIAL_SOURCE_NOT_CONFIGURED:${source}`);
	return getBrightDataSocialDataset(key);
}
