CREATE TYPE "public"."sv_project_status" AS ENUM ('DRAFT', 'ACTIVE', 'ARCHIVED');
CREATE TYPE "public"."sv_scenario_status" AS ENUM ('PROPOSED', 'APPROVED', 'REJECTED');
CREATE TYPE "public"."sv_quote_status" AS ENUM ('DRAFT', 'ISSUED', 'EXPIRED', 'ACCEPTED', 'CANCELLED');
CREATE TYPE "public"."sv_order_status" AS ENUM ('DRAFT', 'CONFIGURING', 'QUOTED', 'AWAITING_PAYMENT', 'PAID_REVIEW_REQUIRED', 'APPROVED', 'QUEUED', 'RUNNING', 'ANALYZING', 'QC_REQUIRED', 'READY', 'DELIVERED', 'PAYMENT_FAILED', 'PREFLIGHT_BLOCKED', 'BUDGET_BLOCKED', 'PROVIDER_BLOCKED', 'CARDINALITY_INCIDENT', 'PARTIAL_FAILURE', 'CANCELLED', 'REFUND_REVIEW');
CREATE TYPE "public"."sv_cycle_status" AS ENUM ('CREATED', 'APPROVED', 'QUEUED', 'RUNNING', 'ANALYZING', 'QC_REQUIRED', 'READY', 'STOPPED', 'FAILED', 'CARDINALITY_INCIDENT');
CREATE TABLE "sv_api_keys" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "name" text NOT NULL, "key_hash" text NOT NULL UNIQUE, "permissions" text[] DEFAULT '{}' NOT NULL, "expires_at" timestamptz, "revoked_at" timestamptz, "created_by" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);

CREATE TABLE "sv_projects" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "name" text NOT NULL, "category" text NOT NULL, "country" text NOT NULL, "region" text, "languages" text[] DEFAULT '{}' NOT NULL, "status" "sv_project_status" DEFAULT 'DRAFT' NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX "sv_projects_org_name_unique" ON "sv_projects" ("organization_id", "name");
CREATE TABLE "sv_prompt_families" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "project_id" uuid NOT NULL REFERENCES "sv_projects"("id"), "intent_type" text NOT NULL, "source" text NOT NULL, "status" "sv_scenario_status" DEFAULT 'PROPOSED' NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "sv_scenarios" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "family_id" uuid NOT NULL REFERENCES "sv_prompt_families"("id"), "text" text NOT NULL, "language" text NOT NULL, "status" "sv_scenario_status" DEFAULT 'PROPOSED' NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "sv_configuration_locks" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "project_id" uuid NOT NULL REFERENCES "sv_projects"("id"), "version" integer NOT NULL, "snapshot" jsonb NOT NULL, "engine_sha" text NOT NULL, "expected_runs" integer NOT NULL, "budget_cap" numeric(12,6) NOT NULL, "created_by" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "sv_quotes" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "project_id" uuid NOT NULL REFERENCES "sv_projects"("id"), "lock_id" uuid NOT NULL REFERENCES "sv_configuration_locks"("id"), "status" "sv_quote_status" DEFAULT 'DRAFT' NOT NULL, "price_amount" numeric(12,2) NOT NULL, "currency" text NOT NULL, "expected_runs" integer NOT NULL, "expires_at" timestamptz NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "sv_orders" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "project_id" uuid NOT NULL REFERENCES "sv_projects"("id"), "quote_id" uuid NOT NULL REFERENCES "sv_quotes"("id"), "lock_id" uuid NOT NULL REFERENCES "sv_configuration_locks"("id"), "status" "sv_order_status" DEFAULT 'DRAFT' NOT NULL, "order_cap" numeric(12,6) NOT NULL, "paid_at" timestamptz, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE TABLE "sv_cycles" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "order_id" uuid NOT NULL REFERENCES "sv_orders"("id"), "lock_id" uuid NOT NULL REFERENCES "sv_configuration_locks"("id"), "status" "sv_cycle_status" DEFAULT 'CREATED' NOT NULL, "expected_runs" integer NOT NULL, "created_runs" integer DEFAULT 0 NOT NULL, "completed_runs" integer DEFAULT 0 NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "updated_at" timestamptz DEFAULT now() NOT NULL);
CREATE INDEX "sv_projects_org_idx" ON "sv_projects" ("organization_id"); CREATE INDEX "sv_prompt_families_project_idx" ON "sv_prompt_families" ("project_id"); CREATE INDEX "sv_scenarios_family_idx" ON "sv_scenarios" ("family_id"); CREATE INDEX "sv_scenarios_org_idx" ON "sv_scenarios" ("organization_id"); CREATE INDEX "sv_locks_project_version_idx" ON "sv_configuration_locks" ("project_id", "version"); CREATE INDEX "sv_quotes_org_idx" ON "sv_quotes" ("organization_id"); CREATE INDEX "sv_quotes_project_idx" ON "sv_quotes" ("project_id"); CREATE INDEX "sv_orders_org_idx" ON "sv_orders" ("organization_id"); CREATE INDEX "sv_orders_status_idx" ON "sv_orders" ("status"); CREATE INDEX "sv_cycles_order_idx" ON "sv_cycles" ("order_id"); CREATE INDEX "sv_cycles_org_idx" ON "sv_cycles" ("organization_id");
CREATE INDEX "sv_api_keys_org_idx" ON "sv_api_keys" ("organization_id"); CREATE INDEX "sv_api_keys_active_idx" ON "sv_api_keys" ("organization_id", "revoked_at");

ALTER TABLE "sv_projects" ENABLE ROW LEVEL SECURITY; ALTER TABLE "sv_prompt_families" ENABLE ROW LEVEL SECURITY; ALTER TABLE "sv_scenarios" ENABLE ROW LEVEL SECURITY; ALTER TABLE "sv_configuration_locks" ENABLE ROW LEVEL SECURITY; ALTER TABLE "sv_quotes" ENABLE ROW LEVEL SECURITY; ALTER TABLE "sv_orders" ENABLE ROW LEVEL SECURITY; ALTER TABLE "sv_cycles" ENABLE ROW LEVEL SECURITY; ALTER TABLE "sv_api_keys" ENABLE ROW LEVEL SECURITY;
