DO $$ BEGIN
 CREATE TYPE "public"."sv_recommendation_run_status" AS ENUM ('RUNNING', 'READY', 'FAILED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
CREATE TABLE IF NOT EXISTS "sv_recommendation_runs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "project_id" uuid NOT NULL REFERENCES "sv_projects"("id"), "idempotency_key" text NOT NULL, "dataset_id" text NOT NULL, "input_hash" text NOT NULL, "rulepack_version" text NOT NULL, "status" "sv_recommendation_run_status" DEFAULT 'RUNNING' NOT NULL, "grounding_status" text DEFAULT 'PENDING' NOT NULL, "action_plan" jsonb, "created_by" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL, "completed_at" timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS "sv_recommendation_runs_org_idempotency_unique" ON "sv_recommendation_runs" ("organization_id", "idempotency_key");
CREATE INDEX IF NOT EXISTS "sv_recommendation_runs_project_idx" ON "sv_recommendation_runs" ("project_id");
CREATE INDEX IF NOT EXISTS "sv_recommendation_runs_org_idx" ON "sv_recommendation_runs" ("organization_id");
CREATE TABLE IF NOT EXISTS "sv_recommendation_manifests" ("id" text PRIMARY KEY NOT NULL, "run_id" uuid NOT NULL REFERENCES "sv_recommendation_runs"("id"), "organization_id" text NOT NULL REFERENCES "organization"("id"), "dataset_id" text NOT NULL, "input_hash" text NOT NULL, "snapshot_ids" text[] DEFAULT '{}' NOT NULL, "evidence_ids" text[] DEFAULT '{}' NOT NULL, "rulepack_version" text NOT NULL, "created_at" timestamptz DEFAULT now() NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "sv_recommendation_manifests_run_unique" ON "sv_recommendation_manifests" ("run_id");
CREATE INDEX IF NOT EXISTS "sv_recommendation_manifests_org_idx" ON "sv_recommendation_manifests" ("organization_id");
CREATE TABLE IF NOT EXISTS "sv_recommendation_evidence" ("id" text NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "run_id" uuid NOT NULL REFERENCES "sv_recommendation_runs"("id"), "snapshot_id" text NOT NULL, "kind" text NOT NULL, "access_class" text NOT NULL, "source_ref" text NOT NULL, "captured_at" text NOT NULL, "subject" text NOT NULL, "text" text NOT NULL, "metadata" jsonb DEFAULT '{}' NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "sv_recommendation_evidence_run_id_unique" ON "sv_recommendation_evidence" ("run_id", "id");
CREATE INDEX IF NOT EXISTS "sv_recommendation_evidence_org_idx" ON "sv_recommendation_evidence" ("organization_id");
CREATE TABLE IF NOT EXISTS "sv_recommendation_findings" ("id" text NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "run_id" uuid NOT NULL REFERENCES "sv_recommendation_runs"("id"), "category" text NOT NULL, "statement" text NOT NULL, "evidence_ids" text[] NOT NULL, "confidence" text NOT NULL, "confidence_score" numeric(5,4) NOT NULL, "severity" text NOT NULL, "unknown" boolean NOT NULL, "rule_id" text NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "sv_recommendation_findings_run_id_unique" ON "sv_recommendation_findings" ("run_id", "id");
CREATE INDEX IF NOT EXISTS "sv_recommendation_findings_org_idx" ON "sv_recommendation_findings" ("organization_id");
CREATE TABLE IF NOT EXISTS "sv_recommendation_actions" ("id" text NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "run_id" uuid NOT NULL REFERENCES "sv_recommendation_runs"("id"), "finding_id" text NOT NULL, "title" text NOT NULL, "action" text NOT NULL, "rationale" text NOT NULL, "evidence_ids" text[] NOT NULL, "priority" text NOT NULL, "effort" text NOT NULL, "confidence" text NOT NULL, "blocked" boolean NOT NULL, "block_reason" text);
CREATE UNIQUE INDEX IF NOT EXISTS "sv_recommendation_actions_run_id_unique" ON "sv_recommendation_actions" ("run_id", "id");
CREATE INDEX IF NOT EXISTS "sv_recommendation_actions_org_idx" ON "sv_recommendation_actions" ("organization_id");
CREATE TABLE IF NOT EXISTS "sv_recommendation_tasks" ("id" text NOT NULL, "organization_id" text NOT NULL REFERENCES "organization"("id"), "run_id" uuid NOT NULL REFERENCES "sv_recommendation_runs"("id"), "recommendation_id" text NOT NULL, "title" text NOT NULL, "horizon" text NOT NULL, "owner" text NOT NULL, "steps" text[] NOT NULL, "evidence_ids" text[] NOT NULL, "verification_plan" text[] NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS "sv_recommendation_tasks_run_id_unique" ON "sv_recommendation_tasks" ("run_id", "id");
CREATE INDEX IF NOT EXISTS "sv_recommendation_tasks_org_idx" ON "sv_recommendation_tasks" ("organization_id");
ALTER TABLE "sv_recommendation_runs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sv_recommendation_manifests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sv_recommendation_evidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sv_recommendation_findings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sv_recommendation_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sv_recommendation_tasks" ENABLE ROW LEVEL SECURITY;
